#!/bin/bash

export SERVER_ENV='pro'

pushd ~/app-root/repo

# Move files where they are expected.
mv public php 
ln -s src/php/main misc
ln -s src/php/lib libs
mv .openshift/htaccess php/.htaccess

# Delete unneeded folders
rm -rf test
rm -rf .openshift

popd

# Tell Git to use the SSH wrapper.
export GIT_SSH=$OPENSHIFT_DATA_DIR/sshwrapper
# Make sure Composer is present.
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi
( unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar update )

