#!/bin/bash

export SERVER_ENV='pro'

pushd ~/app-root/repo

# Move files where they are expected.                                                               
mv public php 
ln -s src/php/main misc
ln -s src/php/lib libs
mv .openshift/htaccess php/.htaccess

# Delete unneeded folders
rm -rf test
rm -rf .openshift

popd
